const app = document.getElementById('app');
let profile = 'Trasporto';
const profiles = ['Ispezione','Trasporto','Creator','Guidata','Professionale','Volo libero'];
function wrap(html){app.innerHTML = `<section class="screen">${html}</section>`}
function home(){wrap(`<div class="topbar"><div><div class="brand">The Probe</div><div class="caption">Intelligent • Intuitive • Universal</div></div><button class="ghost" onclick="archive()">Archivio</button></div><div class="card"><h3>Nuova missione</h3><p class="caption">Scegli il profilo: la dashboard cambierà in base al task.</p></div><div class="grid">${profiles.map(p=>`<div class="card mission" onclick="profile='${p}';preflight()"><span class="tag">${p}</span><h3>${icon(p)} ${p}</h3><p class="caption">${desc(p)}</p></div>`).join('')}</div><button class="cta" onclick="preflight()">Continua con ${profile}</button><div class="small">RF01, RF25, RF26</div></section>`)}
function icon(p){return {Ispezione:'🔍',Trasporto:'📦',Creator:'🎥',Guidata:'🧭',Professionale:'🛠️','Volo libero':'🚁'}[p]||'🚁'}
function desc(p){return {Ispezione:'sensori e ostacoli in evidenza',Trasporto:'peso carico e braccia meccaniche',Creator:'camera, tracking e audio',Guidata:'wizard assistito dall’AI',Professionale:'controlli avanzati', 'Volo libero':'pilotaggio manuale immediato'}[p]}
function preflight(blocked=false){wrap(`<div class="topbar"><button class="ghost" onclick="home()">←</button><div><div class="brand">Check pre-volo</div><div class="caption">Profilo: ${profile}</div></div><span class="tag">Safety</span></div><div class="card"><div class="row"><span>Batteria</span><b class="${blocked?'bad':'ok'}">${blocked?'18%':'86%'}</b></div><div class="bar"><span style="width:${blocked?'18':'86'}%;background:${blocked?'var(--bad)':'var(--ok)'}"></span></div></div>${check('Connettività','Stabile','ok')}${check('Memoria','42 GB liberi','ok')}${check('Camera / Mic','Pronti','ok')}${check('Braccia meccaniche','Calibrate','ok')}${check('Peso carico',blocked?'24 kg > limite':'12 kg / 20 kg',blocked?'bad':'ok')}${check('Sensori essenziali','IMU + prossimità online','ok')}<button class="cta ${blocked?'secondary':''}" ${blocked?'disabled':''} onclick="flight()">${blocked?'Decollo bloccato':'Avvia missione'}</button>${blocked?'<div class="card"><b class="bad">Motivo:</b> batteria insufficiente o carico eccessivo. Riduci il carico o ricarica il drone.</div>':'<button class="ghost" onclick="preflight(true)">Simula condizione critica</button>'}<div class="small">RF02, RF03, RF15, RNF01</div>`)}
function check(label,val,state){return `<div class="check row"><span>${label}</span><b class="${state}">${val}</b></div>`}
function flight(){wrap(`<div class="topbar"><button class="ghost" onclick="preflight()">←</button><div><div class="brand">Missione attiva</div><div class="caption">${profile} • Manuale</div></div><button class="danger" onclick="warning()">STOP</button></div><div class="video"><div class="drone">🚁</div><div class="target"></div><div class="obstacle">⚠ Ostacolo 2.3m SX</div></div><div class="hud"><div class="card"><span class="small">BAT</span><b>74%</b></div><div class="card"><span class="small">ALT</span><b>8m</b></div><div class="card"><span class="small">LINK</span><b class="ok">OK</b></div><div class="card"><span class="small">OBS</span><b class="warn">2.3m</b></div></div><div class="mode-switch"><button class="active">Manuale</button><button onclick="ai()">Assistito</button><button onclick="ai()">Auto</button></div><div class="grid"><button class="cta secondary" onclick="ai()">AI Agent</button><button class="cta secondary" onclick="arms()">Braccia</button><button class="cta secondary" onclick="archive()">Salva</button><button class="cta secondary" onclick="warning()">Warning</button></div><div class="joystick"></div><div class="bottomnav"><button onclick="home()">Home</button><button onclick="flight()">Volo</button><button onclick="ai()">AI</button><button onclick="archive()">Dati</button></div><div class="small">RF04, RF10, RF16, RF17, RF21, RF25</div>`)}
function ai(){wrap(`<div class="topbar"><button class="ghost" onclick="flight()">←</button><div><div class="brand">AI Agent</div><div class="caption">Comandi vocali e testuali</div></div><span class="tag">Assistito</span></div><div class="card"><h3>Comando interpretato</h3><div class="ai-bubble">“Mantieni il soggetto inquadrato e rientra se la batteria scende sotto il 20%.”</div><p class="caption">Azione critica: tracking + possibile rientro. Serve conferma.</p><div class="grid"><button class="cta" onclick="flight()">Conferma</button><button class="cta secondary" onclick="flight()">Annulla</button></div></div><div class="card"><h3>Input vocale</h3><button class="cta secondary">🎙️ Tieni premuto per parlare</button></div><div class="card"><h3>Input testuale</h3><div class="input"><input placeholder="Scrivi un comando…" value="Stabilizzati e prepara presa"/><button class="cta" onclick="arms()">Invia</button></div></div><button class="danger" onclick="flight()">Takeover manuale</button><div class="small">RF07, RF08, RF09, RF20, RNF02, RNF07</div>`)}
function arms(){wrap(`<div class="topbar"><button class="ghost" onclick="flight()">←</button><div><div class="brand">Controllo braccia</div><div class="caption">Drone stabile: sì</div></div><span class="tag">Hover</span></div><div class="arm-visual">🦾 📦 🦾</div><div class="card"><div class="row"><span>Stabilizzazione</span><b class="ok">Confermata</b></div><p class="caption">I comandi di volo sono separati dai comandi braccia.</p></div><div class="grid"><button class="cta secondary">Apri</button><button class="cta secondary">Chiudi</button><button class="cta secondary">Alza</button><button class="cta secondary">Abbassa</button></div><button class="cta" onclick="confirmGrab()">Presa assistita AI</button><button class="danger" onclick="flight()">Takeover volo</button><div class="small">RF11, RF12, RF13, RF14, RNF04, RNF05</div>`)}
function confirmGrab(){wrap(`<div class="topbar"><button class="ghost" onclick="arms()">←</button><div><div class="brand">Presa assistita</div><div class="caption">AI propone allineamento</div></div></div><div class="arm-visual">✅ 📦</div><div class="card"><h3>Conferma umana richiesta</h3><p>Il drone è stabile. Peso stimato: 12 kg. Oggetto allineato al centro.</p><div class="grid"><button class="cta" onclick="flight()">Chiudi braccia</button><button class="cta secondary" onclick="arms()">Annulla</button></div></div><div class="small">RF09, RF14, RF15</div>`)}
function warning(){wrap(`<div class="topbar"><button class="ghost" onclick="flight()">←</button><div><div class="brand">Warning critico</div><div class="caption">Ostacolo + persona nell’area</div></div></div><div class="video"><div class="drone">🚁</div><div class="obstacle">⚠ Persona rilevata 3.1m</div></div><div class="card"><h3 class="warn">AI propone deviazione</h3><p>Deviazione a destra + hover 5s. Le azioni automatiche delicate sono limitate finché la persona resta nell’area.</p><div class="grid"><button class="cta" onclick="flight()">Accetta deviazione</button><button class="cta secondary" onclick="flight()">Manuale</button></div><button class="danger" onclick="flight()">Stop / Hover</button></div><div class="small">RF18, RF19, RF20, RNF01, RNF02</div>`)}
function archive(){wrap(`<div class="topbar"><button class="ghost" onclick="home()">←</button><div><div class="brand">Archivio missioni</div><div class="caption">Foto, video, audio, log e telemetria</div></div></div><div class="card"><div class="input"><input placeholder="Cerca per data, profilo, luogo o tag…"/><button class="cta secondary">Filtra</button></div></div><div class="card"><div class="archive-item"><b>Trasporto • 25/06/2026</b><p class="caption">Video, telemetria, 3 warning, backup cloud completato</p></div><div class="archive-item"><b>Creator • Tracking soggetto</b><p class="caption">42 foto, 1 video, audio ambiente</p></div><div class="archive-item"><b>Ispezione • Magazzino</b><p class="caption">Log ostacoli, note operatore, pacchetto condivisibile</p></div></div><div class="grid"><button class="cta secondary">Backup cloud</button><button class="cta secondary">Condividi</button></div><div class="small">RF27, RF28, RF29, RF30</div>`)}
home();
